### ISSUE TITLE
ARRRmada @TODO

### ISSUE THREAD

**Issue by scott-ftf** [ARRRmada/ARRRmada.com#14]
### - [ ]  Develop a Merchant announcement automation
Initial thought is to utilize Github Workflow actions. When a announcement markdown is pushed to a "announcements" directory, the workflow will generate a tweet on the ARRRmada twitter account, and announcement post on teh Pirate Github.

#### BTCpay
https://discord.com/channels/512188534111862784/1063021016894418995
- [ ] Install and test
- [ ] Update Documentation

#### Piratepay
https://discord.com/channels/512188534111862784/1063009226299015168
- [ ] Install and test
- [ ] Update Documentation

#### Veruspay
- [ ] Install and test
- [ ] Update Documentation

### - [ ]  Develop a Lite Client based Payment Gateway
- [ ] Research best approach

**Comment by zseko** [comment]
**BTCPay Docker:**
https://github.com/PirateNetwork/btcpayserver-docker
_Docker resources for hosting BTCPayServer easily_

**BTCPayServer:**
https://github.com/PirateNetwork/btcpayserver
https://www.youtube.com/watch?v=VtwGeMXMo40
_Accept Bitcoin payments. Free, open-source & self-hosted, Bitcoin payment processor._

**Pirate BTCpay:**
https://github.com/PirateNetwork/pirate-btcpay
https://hhanh01.github.io/pirate-btcpay/

Developer: https://github.com/hhanh01

**PiratePay:**
https://github.com/CryptocurrencyCheckout/PiratePay
PiratePay Guide:
https://cryptocurrencycheckout.com/guides/piratepay
PiratePay WooCommerce Plugin:
https://github.com/CryptocurrencyCheckout/PiratePay-Woocommerce-Plugin

**VerusPay:**
https://github.com/monkins1010/VerusPay

**Comment by s-ftf** [comment]
@zseko 

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Fleet Pings You. Message me on https://keybase.io/sftf

-----BEGIN PGP SIGNATURE-----

iHUEARYKAB0WIQTlFC7RuMaDp2CX4EAbf5fNhNk2xwUCaX7VRwAKCRAbf5fNhNk2
x+P0AP4vbhpldYPapAVgePzSfC0StbYVPg31BE4cvW45UAuW8wD9GCNoqe7kr4ob
6pFzWCEpUe93tmFkfq++gNY98zAmcwE=
=4CNt
-----END PGP SIGNATURE-----
